title: "GEMmaker Quality Report"
subtitle: "GEMmaker is a Nextflow workflow for large-scale gene expression sample processing, expression-level quantification and Gene Expression Matrix (GEM) construction."
intro_text: "Results from GEMmaker are useful for differential gene expression and gene co-expression network analyses. This report is the MultiQC summary of the GEMmaker workflow results."
custom_logo: './images/GEMmaker-logo-sm.png'
